name: login_minimalist
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf_viewer_plugin: ^1.0.0+2
  splashscreen: ^1.2.0
  shared_preferences: ^0.4.2
  font_awesome_flutter: ^8.2.0
  firebase_auth: ^0.11.1+10
  cloud_firestore: ^0.13.7
  photo_view: ^0.9.2
  google_sign_in: ^4.0.4
  gradient_widgets: ^0.5.2
  http: ^0.12.0+2
  plugin_scaffold: ^1.1.1
  image_picker: ^0.6.1+8
  flutter_pdfview: ^1.0.3
  path_provider: ^1.6.11
  flutter_launcher_icons: ^0.7.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  auto_size_text: ^2.0.2
  flutter_spinkit: ^3.1.0
  flutter_auth_buttons: ^0.8.0
  material_design_icons_flutter: 4.0.5345
  email_validator: ^1.0.0
  flutter_full_pdf_viewer: ^1.0.6
  flutter_plugin_pdf_viewer: ^1.0.7
  crypto: ^2.0.6
  fluttertoast: ^3.0.4
  url_launcher: ^5.5.0
  flutter_responsive: ^0.0.4
  flutter_screenutil: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


  # assets:
  #- assets/loading.gif
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/loading.gif
    - assets/welcome.gif
    - assets/welcometran.gif
    - assets/bio.gif
    - assets/welcome1.gif
    - assets/signin.gif
    - assets/settings.png
    - assets/profile.png

    - assets/subjects.png
    - assets/statistics.png
    - assets/feedback.png
    - assets/version.png
    - assets/images/pritish.jpg
    - assets/images/abhijit.jpg
    - assets/sample.pdf
    - assets/class6.gif
    - assets/class7.gif
    - assets/class8.gif
    - assets/class9.gif
    - assets/class10.gif


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/done.json




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
fonts:
  - family: Poppins
    fonts:
      - asset: font/Poppins-Medium.ttf
      - asset: font/Poppins-Regular.ttf
        weight: 500

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages